run:
  timeout: 5m
  tests: true

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - revive
    - gocritic
    - noctx
    - bodyclose
    - exhaustive
    - godot
    - gofumpt
    - whitespace
    - wrapcheck
    - testifylint

linters-settings:
  goimports:
    local-prefixes: github.com/vxcontrol/langchaingo
  revive:
    rules:
      - name: exported
        arguments:
          - disableStutteringCheck
  godot:
    scope: declarations
    capital: false
  wrapcheck:
    ignorePackageGlobs:
      - github.com/vxcontrol/langchaingo/*
  exhaustive:
    default-signifies-exhaustive: true

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - wrapcheck
        - errcheck
    - path: examples/
      linters:
        - wrapcheck
        - godot
  max-issues-per-linter: 0
  max-same-issues: 0
